# Generated by Django 2.1.7 on 2019-02-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190222_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingridients',
            new_name='ingridients',
        ),
    ]
